# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

ape_perm <- function(m) {
    .Call(`_manteltest_ape_perm`, m)
}

ape_zstat <- function(m1, m2) {
    .Call(`_manteltest_ape_zstat`, m1, m2)
}

rcpp_hello_world <- function() {
    .Call(`_manteltest_rcpp_hello_world`)
}

